### ISSUE TITLE
Possibly bad request format in SDK

### ISSUE THREAD

**Issue by TrentZiften** [box/box-python-sdk#243]
When trying to run "client.as_user(u).folder('0').get_items(10)" in an interactive shell, I am shown the following traceback

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/boxsdk/util/api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/boxsdk/object/folder.py", line 155, in get_items
    box_response = self._session.get(url, params=params)
  File "/usr/local/lib/python3.5/site-packages/boxsdk/session/box_session.py", line 449, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/boxsdk/session/box_session.py", line 350, in _prepare_and_send_request
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/boxsdk/session/box_session.py", line 437, in _make_request
    self._raise_on_unsuccessful_request(network_response, expect_json_response, method, url)
  File "/usr/local/lib/python3.5/site-packages/boxsdk/session/box_session.py", line 288, in _raise_on_unsuccessful_request
    network_response=network_response
boxsdk.exception.BoxAPIException:
Message: None
Status: 403
Code: None
Request id: None
Headers: {'Age': '2', 'Server': 'Server', 'WWW-Authenticate': 'Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."', 'Connection': 'keep-alive', 'Date': 'Wed, 20 Sep 2017 20:25:21 GMT', 'Content-Length': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'}
URL: https://api.box.com/2.0/folders/0/items
Method: GET
Context info: None

u is a valid user object, and this particular user can log into the webgui and view folders. Even using folder names that show up there result in the same trace. This has been tested with 2.0.0a9, in both Python2 and Python3, with the same results. I was requested to file this report by support member Johannes Frank.

**Comment by jmoldow** [comment]
The problem is probably not with `u` or with the SDK, but with the client. One or more of these things is probably the case:
- The application is not configured to support the `As-User` feature (it lacks the necessary scope).
- The authenticated user does not have permissions to use the `As-User` feature (it isn't an admin or a service account).
- The authenticated user does not have permissions to impersonate user `u`.

For the first issue, see https://developer.box.com/docs/configuring-box-platform#section-3-enabling-app-auth-and-app-users and https://developer.box.com/docs/configuring-service-accounts#section-5-select-advanced-features .
