### ISSUE TITLE
boxsdk.exception.BoxOAuthException forJWT authorization Python

### ISSUE THREAD

**Issue by pikachika** [box/box-python-sdk#384]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Im trying to get QAuth2.0 with Server JWT authorized to connect my app to Enterprise account in Box. 

 
This is my code:

 
auth = JWTAuth(
client_id='*******************',
client_secret='*************************',
enterprise_id='*****',
jwt_key_id='********',
rsa_private_key_file_sys_path='/Users/*****/python_alert/private.pem',
rsa_private_key_passphrase='****',
store_tokens=None,
)

access_token = auth.authenticate_instance()

client = Client(auth)

My enterprise admin has authorized my app as well. Can someone help please?

### Versions Used

Python: 2.7

### Error Message, Including Traceback
This is the error I get:

 

No handlers could be found for logger "boxsdk.network.default_network"

Traceback (most recent call last):

  File "box.py", line 33, in <module>

    access_token = auth.authenticate_instance()

  File "/Library/Python/2.7/site-packages/boxsdk/auth/jwt_auth.py", line 384, in authenticate_instance

    return self._auth_with_jwt(self._enterprise_id, 'enterprise')

  File "/Library/Python/2.7/site-packages/boxsdk/auth/jwt_auth.py", line 243, in _auth_with_jwt

    return self._construct_and_send_jwt_auth(sub, sub_type)

  File "/Library/Python/2.7/site-packages/boxsdk/auth/jwt_auth.py", line 219, in _construct_and_send_jwt_auth

    return self.send_token_request(data, access_token=None, expect_refresh_token=False)[0]

  File "/Library/Python/2.7/site-packages/boxsdk/auth/oauth2.py", line 401, in send_token_request

    token_response = self._execute_token_request(data, access_token, expect_refresh_token)

  File "/Library/Python/2.7/site-packages/boxsdk/auth/oauth2.py", line 347, in _execute_token_request

    six.raise_from(self._oauth_exception(box_api_excpetion.network_response, url), box_api_excpetion)

  File "/Library/Python/2.7/site-packages/six.py", line 737, in raise_from

    raise value

boxsdk.exception.BoxOAuthException:

Message: None

Status: 400

URL: https://api.box.com/oauth2/token

Method: POST

Headers: {'Content-Length': '145', 'Content-Encoding': 'gzip', 'Set-Cookie': 'box_visitor_id=5c1a9937dd6033.60743312; expires=Thu, 19-Dec-2019 19:17:11 GMT; Max-Age=31536000; path=/; domain=.box.com; secure, bv=OPS-42764; expires=Wed, 26-Dec-2018 19:17:11 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure, cn=66; expires=Thu, 19-Dec-2019 19:17:11 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure, site_preference=desktop; path=/; domain=.box.com; secure', 'Age': '1', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Encoding', 'Connection': 'keep-alive', 'Cache-Control': 'no-store', 'Date': 'Wed, 19 Dec 2018 19:17:12 GMT', 'Content-Type': 'application/json'}

**Comment by carycheng** [comment]
Hey @pikachika, 

We tracked down your request in the server logs. What it looks like might be happening is your public key that you uploaded in the developer console is improperly formatted.

The correct format looks like this:
```
-----BEGIN PUBLIC KEY-----
//PUBLIC KEY INFO
-----END PUBLIC KEY-----
```

**Comment by pikachika** [comment]
Hi Cary,

I am getting the same error message even after fixing the public key in box developer console.

**Comment by pikachika** [comment]
Sorry, problem was solved once i re-generated private key. But now I get this error:

Traceback (most recent call last):
  File "box.py", line 39, in <module>
    store_tokens=None
  File "/Library/Python/2.7/site-packages/boxsdk/auth/jwt_auth.py", line 141, in __init__
    passphrase=rsa_private_key_passphrase,
  File "/Library/Python/2.7/site-packages/boxsdk/auth/jwt_auth.py", line 421, in _normalize_rsa_private_key
    backend=default_backend(),
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1016, in load_pem_private_key
    password,
  File "/Library/Python/2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1241, in _load_key
    "Password was given but private key is not encrypted.")
TypeError: Password was given but private key is not encrypted.

**Comment by carycheng** [comment]
Please reopen if this issue persists, thank you!

**Comment by kennedyjosh** [comment]
Hi @carycheng, I'm getting pretty much the exact same issue, but I'm doing regular OAuth2 verification (not JWT). Here is my code:
```
from flask import Flask, redirect, request
from boxsdk import Client
from boxsdk import OAuth2

import config_oauth
import requests
import logging

app = Flask(__name__)

# Create new OAuth client & csrf token                                                                                                      
oauth = OAuth2(
  client_id=config_oauth.client_id,
  client_secret=config_oauth.client_secret
)
csrf_token = ''


# Create Box redirect URI with csrf token and redirect user                                                                                 
@app.route('/login')
def start():
  global csrf_token
  auth_url, csrf_token = oauth.get_authorization_url(config_oauth.redirect_uri)

  return redirect(auth_url)

# Fetch access token and make authenticated request                                                                                         
@app.route('/get')
def capture():
  # Capture auth code and csrf token via state                                                                                              
  code = request.args.get('code')
  state = request.args.get('state')

  # If csrf token matches, fetch tokens                                                                                                     
  assert state == csrf_token
  #print(code)                                                                                                                              
  #print(oauth.authenticate(code))                                                                                                          
  access_token, refresh_token = oauth.authenticate(code)

  client = Client(oauth)
  print(client)

  return "Success"
```

Here is the exact error I receive:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/josh/Desktop/rips/check.py", line 38, in capture
    access_token, refresh_token = oauth.authenticate(code)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boxsdk/auth/oauth2.py", line 204, in authenticate
    return self.send_token_request(data, access_token=None)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boxsdk/auth/oauth2.py", line 401, in send_token_request
    token_response = self._execute_token_request(data, access_token, expect_refresh_token)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boxsdk/auth/oauth2.py", line 347, in _execute_token_request
    six.raise_from(self._oauth_exception(box_api_excpetion.network_response, url), box_api_excpetion)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
BoxOAuthException: 
Message: None
Status: 400
URL: https://api.box.com/oauth2/token
Method: POST
Headers: {'Content-Length': '83', 'Set-Cookie': 'box_visitor_id=5c723b2a1644f6.51280284; expires=Mon, 24-Feb-2020 06:35:22 GMT; Max-Age=31536000; path=/; domain=.box.com; secure, bv=OPS-42882; expires=Sun, 03-Mar-2019 06:35:22 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure, cn=28; expires=Mon, 24-Feb-2020 06:35:22 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure, site_preference=desktop; path=/; domain=.box.com; secure', 'Age': '0', 'Strict-Transport-Security': 'max-age=31536000', 'Connection': 'keep-alive', 'Cache-Control': 'no-store', 'Date': 'Sun, 24 Feb 2019 06:35:22 GMT', 'Content-Type': 'application/json'}
```

**Comment by carycheng** [comment]
Hey @kennedyjosh,

We looked through our server logs and were able to locate your error. Can you please check if your client id and client secret are correct? It seems the issue could perhaps be stemming from there.

Let us know if this issue persists, thank you!

**Comment by kennedyjosh** [comment]
Hi @carycheng,

Thanks for the quick response. The issue was as you described: I had the wrong client_secret. Do you think you could improve error handling to return a more useful error message for cases like this in the future? 

Thanks for your help!
