### ISSUE TITLE
v2.2.0 can not install

### ISSUE THREAD

**Issue by rawsk** [box/box-python-sdk#405]
boxsdk v2.2.0 can not install.
```
$ pip install boxsdk==2.2.0
...
Exception:
Traceback (most recent call last):
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/wheel.py", line 314, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Users/jumpei/workspace/temp/lib/python3.7/site-packages/pip/_internal/wheel.py", line 274, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /Users/jumpei/workspace/temp/lib/python3.7/site-packages/boxsdk-2.2.0.dist-info, /Users/jumpei/workspace/temp/lib/python3.7/site-packages/boxsdk-2.1.0.dist-info
```

I investigated the cause of the error.
```
$ pip download boxsdk==2.2.0
Collecting boxsdk==2.2.0
  Using cached https://files.pythonhosted.org/packages/10/1c/89ee598ae557b5d482f686777e8e27c613c29b34c5d3c8046d19b84dae70/boxsdk-2.2.0-py2.py3-none-any.whl
  Saved ./boxsdk-2.2.0-py2.py3-none-any.whl
...
$ unzip -d boxsdk boxsdk-2.2.0-py2.py3-none-any.whl
$ cd boxsdk
$ ls 
boxsdk	boxsdk-2.1.0.dist-info	boxsdk-2.2.0.dist-info
```
`boxsdk-2.1.0.dist-info/` and `boxsdk-2.2.0.dist-info/` existed in the library.
Probably `boxsdk-2.1.0.dist-info/` is the cause of the error.

**Comment by mmarceau** [comment]
Came here for same reason. Unable to install

**Comment by mmarceau** [comment]
I've created a support ticket with Box for anyone else looking. TicketId: 1847153

**Comment by mattwiller** [comment]
@rawsk @mmarceau We're on it — we'll push out a v2.2.1 release today that should be identical to the v2.2.0 one (just without the erroneous `.dist-info`).  In the meantime, you may want to consider using v2.1.0 until we can get a corrected release out.

**Comment by carycheng** [comment]
Hey @rawsk @mmarceau,

We just pushed out v2.2.1 of the Python SDK that should resolve this issue. We apologize for any inconvenience this may have caused. 

If you have any further issues or questions going forward please do not hesitate to reach out!

**Comment by rawsk** [comment]
Thank you for fixing! 
Can I close this issue? or will you?
