### ISSUE TITLE
Python get() function is always returning a boxsdk.exception.BoxOAuthException with status 400 when using JWT

### ISSUE THREAD

**Issue by actuallyaswin** [box/box-python-sdk#409]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am able to connect to a Python Box SDK client using the following code:
```python
import boxsdk
from boxsdk import JWTAuth
from boxsdk import Client
sdk = JWTAuth.from_settings_file('PATH_TO_MY_GENERATED_JSON/xxxxx_xxxxxxxx_config.json')
client = Client(sdk)
```
I have "x"ed out the Enterprise ID and public key IDs in the above, but assume both are valid, and that the contents of this JSON file are exactly as-is when obtaining a file by pressing _Generate a Public/Private Keypair_ at https://iu.app.box.com/developers/console/app/. 

When I try to run the following code afterwards:

```python
user = client.user().get()
print('The current user ID is {0}'.format(user.id))
```

The program fails on the "get()" call. This is true for Users, Folders, Files, and other Box SDK object types. Other routines such as "get_items()" works file, but "get()" fails. This means I am unable to view the id and name (or other attributes) of any item in my Box.

### Versions Used
Box Python SDK: 2.2.1
Python: 3.6.6

### Steps to Reproduce
The steps to reproduce are outlined in the above description..

### Error Message, Including Traceback
```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/util/api_call_decorator.py", line 71, in call
    return method(*args, **kwargs)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/object/base_object.py", line 85, in get
    box_response = self._session.get(url, params=params, headers=headers)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/session/session.py", line 94, in get
    return self.request('GET', url, **kwargs)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/session/session.py", line 150, in request
    response = self._prepare_and_send_request(method, url, **kwargs)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/session/session.py", line 372, in _prepare_and_send_request
    network_response = self._send_request(request, **kwargs)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/session/session.py", line 556, in _send_request
    access_token = self._renew_session(None)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/session/session.py", line 500, in _renew_session
    new_access_token, _ = self._oauth.refresh(access_token_used)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/oauth2.py", line 266, in refresh
    access_token, refresh_token = self._refresh(access_token_to_refresh)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/jwt_auth.py", line 394, in _refresh
    new_access_token = self.authenticate_instance()
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/jwt_auth.py", line 384, in authenticate_instance
    return self._auth_with_jwt(self._enterprise_id, 'enterprise')
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/jwt_auth.py", line 243, in _auth_with_jwt
    return self._construct_and_send_jwt_auth(sub, sub_type)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/jwt_auth.py", line 219, in _construct_and_send_jwt_auth
    return self.send_token_request(data, access_token=None, expect_refresh_token=False)[0]
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/oauth2.py", line 401, in send_token_request
    token_response = self._execute_token_request(data, access_token, expect_refresh_token)
  File "/Users/myusername/.pyenv/versions/3.6.6/lib/python3.6/site-packages/boxsdk/auth/oauth2.py", line 347, in _execute_token_request
    six.raise_from(self._oauth_exception(box_api_excpetion.network_response, url), box_api_excpetion)
  File "<string>", line 3, in raise_from
boxsdk.exception.BoxOAuthException: 
Message: None
Status: 400
URL: https://api.box.com/oauth2/token
Method: POST
Headers: {'Date': 'Thu, 07 Mar 2019 06:31:05 GMT', 'Content-Type': 'application/json', 'Content-Length': '104', 'Connection': 'keep-alive', 'Cache-Control': 'no-store', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'box_visitor_id=5c80baa9d5e955.47042699; expires=Sat, 07-Mar-2020 06:31:05 GMT; Max-Age=31622400; path=/; domain=.box.com; secure, bv=OPS-42903; expires=Thu, 14-Mar-2019 05:31:05 GMT; Max-Age=601200; path=/; domain=.app.box.com; secure, cn=30; expires=Sat, 07-Mar-2020 06:31:05 GMT; Max-Age=31622400; path=/; domain=.app.box.com; secure, site_preference=desktop; path=/; domain=.box.com; secure', 'Age': '0'}
```

I have verified that the clientID and clientSecret inside of my config.json are both valid and match the values shown in my Box Developer dashboard.

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @actuallyaswin,

We were able to track down your request and the error you seem to be coming across is you need to enable your application for your enterprise. The place to enable your application is through the Admin Console.

If you take a look specifically at Step 3 in the below article it details how to go about enabling your application or maybe for your Enterprise Admin to enable your application.

https://developer.box.com/docs/setting-up-a-jwt-app

Please let us know if you run into any issues!

**Comment by carycheng** [comment]
Hey @actuallyaswin,

We will be closing this issue for now. However, if you run into any issues at all please do not hesitate to reopen this current issue or create a new one.

We will do our best to resolve it in a timely fashion.

Thanks!
