### ISSUE TITLE
AssertionError: Multiple .dist-info directories since March 28th release. 

### ISSUE THREAD

**Issue by dlevinson5** [box/box-python-sdk#416]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Starting on March 28th, 2018 the pip install of boxsdk[jwt] started returning "Get error "AssertionError: Multiple .dist-info directories: /usr/local/lib/python3.6/site-packages/boxsdk-2.3.0.dist-info, /usr/local/lib/python3.6/site-packages/boxsdk-2.2.2.dist-info"

### Versions Used
Box Python SDK: Latest version
Python: 3.6

### Steps to Reproduce

1. Run *pip3 install "boxsdk[jwt]"*
2. Get error "AssertionError: Multiple .dist-info directories: /usr/local/lib/python3.6/site-packages/boxsdk-2.3.0.dist-info, /usr/local/lib/python3.6/site-packages/boxsdk-2.2.2.dist-info"

### Error Message, Including Traceback
```
Step 7/11 : RUN pip3 install "boxsdk[jwt]"
 ---> Running in 6d0e8f0e53d7
Collecting boxsdk[jwt]
  Downloading https://files.pythonhosted.org/packages/f3/45/ce899eb0693fd72da4af1b3f6d2900fc79717def7eab684a2d3ad72d5dbd/boxsdk-2.3.0-py2.py3-none-any.whl (135kB)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python3.6/site-packages (from boxsdk[jwt]) (2.21.0)
Requirement already satisfied: requests-toolbelt<1.0.0,>=0.4.0 in /usr/local/lib/python3.6/site-packages (from boxsdk[jwt]) (0.9.1)
Collecting attrs>=17.3.0 (from boxsdk[jwt])
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/site-packages (from boxsdk[jwt]) (1.12.0)
Collecting wrapt>=1.10.1 (from boxsdk[jwt])
  Downloading https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gz
Requirement already satisfied: cryptography>=0.9.2; extra == "jwt" in /usr/local/lib/python3.6/site-packages (from boxsdk[jwt]) (2.6.1)
Collecting pyjwt>=1.3.0; extra == "jwt" (from boxsdk[jwt])
  Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.4.3->boxsdk[jwt]) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.4.3->boxsdk[jwt]) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.4.3->boxsdk[jwt]) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.4.3->boxsdk[jwt]) (2.8)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/site-packages (from cryptography>=0.9.2; extra == "jwt"->boxsdk[jwt]) (1.12.2)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/site-packages (from cryptography>=0.9.2; extra == "jwt"->boxsdk[jwt]) (0.24.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=0.9.2; extra == "jwt"->boxsdk[jwt]) (2.19)
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/89/67/41/63cbf0f6ac0a6156588b9587be4db5565f8c6d8ccef98202fc
Successfully built wrapt
Installing collected packages: attrs, wrapt, pyjwt, boxsdk
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/wheel.py", line 426, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/wheel.py", line 375, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /usr/local/lib/python3.6/site-packages/boxsdk-2.3.0.dist-info, /usr/local/lib/python3.6/site-packages/boxsdk-2.2.2.dist-info
```

[sdk-docs]: ./docs/usage
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@dlevinson5 Thank you for letting us know — sorry for the inconvenience that this causes!  We'll take a look and get a fixed version released today.

**Comment by carycheng** [comment]
Hey @dlevinson5, 

Apologies again for any inconvenience! The new version of v2.3.2 is out now and should be fixed. Please let us know if it's working!
