### ISSUE TITLE
Report helpful error message for missing "jwt" dependency

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk#526]
### Is your feature request related to a problem? Please describe.

As is known from closed issue (https://github.com/box/box-python-sdk/issues/387) if you don't `pip install "boxsdk[jwt]", and use the JWT authorization, you get a somewhat confusing message:

```
  File "/Users/first.last/workspace/repo_name/box/../lib/box.py", line 70, in get_jwt_client
    auth = boxsdk.JWTAuth.from_settings_file(load_config(self.app_name))
AttributeError: 'NoneType' object has no attribute 'from_settings_file'
```

### Describe the solution you'd like

Return an error message instead that at least suggests "Did you try pip install boxsdk[jwt]?" when JWTAuth isn't going to work.

### Additional context
Using sdk version `boxsdk 2.9.0`

**Comment by sujaygarlanka** [comment]
@supermitch Thank you for the feedback! We will take a look at this.

**Comment by sujaygarlanka** [comment]
@supermitch We are currently prioritizing bugs over enhancements in all our SDKs, so it may take a while for us to get to some of these. If are interested in submitting PRs for the enhancements, we would love to take a look!

**Comment by regoawt** [comment]
I've just been hit with the same issue as @federicojasson - issue with `cryptography` bindings when deployed on AWS Lambda being swallowed and raised as `AttributeError: 'NoneType' object has no attribute 'from_settings_dictionary'`. 

Interestingly, the original error does get surfaced correctly when I import directly:
```
from boxsdk.auth.jwtauth import JWTAuth
```
rather than
```
from boxsdk import JWTAuth
```

**Comment by bvrs-atri** [comment]
Hi @regoawt, I'm facing the same issue when trying to use Boxsdk as a layer for Lambda Function.

This is what i followed to create layer. [AWS Docs](https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/layer-python/layer)

I have tried installing only Boxsdk (without boxsdk[jwt]) and both of them at once as well. But i still see the issue 

`[ERROR] AttributeError: 'NoneType' object has no attribute 'from_settings_dictionary'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 70, in lambda_handler
    auth = JWTAuth.from_settings_dictionary(json.loads(secret))`

Runtime : Python 3.11

Anyway to solve this ?
