### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by toanngkh** [box/box-python-sdk#601]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I'm using JWTAuth to authenticate box_auth_conf json file. It gives me the following error at the import statement:
ModuleNotFoundError: No module named 'attr'
I'm not sure if it's related but this code has been working for 2 years. I'm using Anaconda as package manager, but I installed boxsdk via pip. Yesterday I updated a package in Anaconda called SQLAlchemy. This morning I found this code about JWTAuth broke. So I think they may be related.

### Steps to Reproduce
1. Install boxsdk, boxsdk[jwt]
2. From boxsdk import JWTAuth
3. See error

### Expected Behavior
No error as it's been working for 2 years

### Error Message, Including Stack Trace
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Apps\domestic\util.py", line 11, in <module>
    from boxsdk import JWTAuth
  File "C:\Users\svc_appstg01\AppData\Local\Continuum\anaconda3\envs\kosmos\lib\site-packages\boxsdk\__init__.py", line 5, in <module>
    from .auth import JWTAuth, OAuth2
  File "C:\Users\svc_appstg01\AppData\Local\Continuum\anaconda3\envs\kosmos\lib\site-packages\boxsdk\auth\__init__.py", line 5, in <module>
    from .cooperatively_managed_oauth2 import CooperativelyManagedOAuth2
  File "C:\Users\svc_appstg01\AppData\Local\Continuum\anaconda3\envs\kosmos\lib\site-packages\boxsdk\auth\cooperatively_managed_oauth2.py", line 4, in <module>
    from .oauth2 import OAuth2
  File "C:\Users\svc_appstg01\AppData\Local\Continuum\anaconda3\envs\kosmos\lib\site-packages\boxsdk\auth\oauth2.py", line 18, in <module>
    from ..exception import BoxOAuthException, BoxAPIException
  File "C:\Users\svc_appstg01\AppData\Local\Continuum\anaconda3\envs\kosmos\lib\site-packages\boxsdk\exception.py", line 5, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

### Versions Used
Python SDK: 2.3.2, updated to 2.12 still have error
Python: 3.6.10

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@toanngkh I think the sqlalchemy upgrade may be causing the problem. Our SDK use on it. When we run our tests, we look for an sqlalchemy version 1.4.0 or below as shown [here](https://github.com/box/box-python-sdk/blob/6563264428180affe4b499150957129421b60002/setup.py#L97). What sqlalchemy version are you using? A good solution may to create python virtual environment, so you have separate environment from your global one and install the SDK in that. These are some steps to get you started if you are interested in going that route https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/26/python-virtual-env/.

**Comment by toanngkh** [comment]
I think before the update it was 1.3.x, yesterday I updated to latest version. I created new Conda virtual environment with both latest versions of boxsdk (2.12) and sqlalchemy (1.4.15) and it works.

**Comment by toanngkh** [comment]
Create new environment solved the issue.
