### ISSUE TITLE
connection time out 

### ISSUE THREAD

**Issue by danyal123** [box/box-python-sdk#83]
I have the long polling function working but it times out within 10-15 seconds is there a way to keep the connection  live for longer
'''
def read_tokens():
    try :
        f=open('/var/lock/box_locks/token.txt','rU')
        a=(f.read())
        tokens=(json.JSONDecoder().decode(a))
        access_token= tokens['access_token']
        refresh_token=tokens['refresh_token']
        print ('\n','this is a new access_token',access_token)
        return access_token,refresh_token
    except :
        print ('method has faild check tokens')
        exception_file()
access_token,refresh_token=read_tokens()

def events():
    for event in client.events().generate_events_with_long_polling():
        try:
            print(event)
            ev=open('events.txt','a')
            json.dump(event,ev,sort_keys=True)
            ev.write('\n')
            ev.close()
            return ev
        except :
            read_tokens()
            continue
            return ev

events()
'''

**Comment by jmoldow** [comment]
What version of requests do you have installed (``pip show requests`` on the command line), and what exception is being raised?

``generate_events_with_long_polling()`` is supposed to catch ``Timeout`` exceptions and continue with the long polling. So you shouldn't be seeing those exceptions. It's possibly that ``requests`` has a bug and is raising a different kind of exception. So please let us know which version, and which exception.

Also, if you use ``return`` inside a for-loop, you will always exit the loop after it reaches that point.

**Comment by danyal123** [comment]
this is the list of errors that i am getting


Traceback (most recent call last):
  File "long_polling_events.py", line 90, in events
    for event in client.events().generate_events_with_long_polling():
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/object/events.py", line 132, in generate_events_with_long_polling
    for event, next_stream_position in self._get_all_events_since(stream_position):
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/object/events.py", line 68, in _get_all_events_since
    events = self.get_events(stream_position=next_stream_position, limit=100)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/object/events.py", line 46, in get_events
    box_response = self._session.get(url, params=params)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/session/box_session.py", line 364, in get
    response = self._prepare_and_send_request('GET', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/session/box_session.py", line 275, in _prepare_and_send_request
    **kwargs
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/session/box_session.py", line 349, in _make_request
    **kwargs
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/session/box_session.py", line 159, in _retry_request_if_necessary
    self._renew_session(network_response.access_token_used)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/session/box_session.py", line 124, in _renew_session
    self._oauth.refresh(access_token_used)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/auth/oauth2.py", line 177, in refresh
    return self._refresh(access_token_to_refresh)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/auth/oauth2.py", line 159, in _refresh
    return self.send_token_request(data, access_token)
  File "/usr/lib/python2.6/site-packages/boxsdk-1.2.2-py2.6.egg/boxsdk/auth/oauth2.py", line 225, in send_token_request
    raise BoxOAuthException(network_response.status_code, network_response.content, url, 'POST')
BoxOAuthException:
Message: {"error":"invalid_request","error_description":"No \"refresh_token\" parameter found"}
Status: 400
URL: https://api.box.com/oauth2/token
Method: POST

**Comment by jmoldow** [comment]
This has nothing to do with `generate_events_with_long_polling()`. Your `client` object has neither a valid access token (hence the `_renew_session`) nor a refresh token (hence the 400 error you're seeing).

When you create the `client`, you must log in and generate a new access token and refresh token. Alternatively, you can save and later re-use your latest refresh token. But the access token always expires after an hour. The refresh token lasts a lot longer, HOWEVER it becomes invalid every time you use it to generate a new access token, refresh token pair.

**Comment by danyal123** [comment]
but the read token() gets a new set of valid tokens every time it runs, also if the access token lasts for an hour why do i get timed out in a matter of seconds
